### ISSUE TITLE
In DB query listener, capture the code location in a generic way

### ISSUE THREAD

**Issue by asgrim** [scoutapp/scout-apm-laravel#13]
Replacing `todo` in code with an issue:

```php
// TODO: figure out how to capture code location in a generic way (also specifically for db calls)
// From Laravel DebugBar - https://github.com/barryvdh/laravel-debugbar/blob/master/src/DataCollector/QueryCollector.php#L193
```

**Comment by cschneid** [comment]
After I wrote that we did implement the backtrace capture code, although it's not fully tested/tweaked yet to work well. The big thing we want is to capture the user's code location, not a trace into the internal of Laravel.

**Comment by asgrim** [comment]
In that case: this depends on scoutapp/scout-apm-php#61
