### ISSUE TITLE
Test against custom blade directives

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout-apm-laravel#45]
We had a report of an issue with a custom blade directive.

```
I did notice that installing your Laravel package broke a custom Blade directive
that we use from the spatie/laravel-permission package.
What’s the best way to troubleshoot this?
For now, I was able to refactor usage of that `@role` directive,
but I’d like to get that fixed and understand why it broke.
```

I'm asking for any exception or backtrace, but this is worth looking into.

**Comment by cschneid** [comment]
I believe the blade ext is this: https://github.com/spatie/laravel-permission/blob/master/src/PermissionServiceProvider.php#L67-L72

**Comment by cschneid** [comment]
From the customer:

"No error was caused by the Blade directive, it just rendered the Blade code as text, which broke some conditional logic on the page."

**Comment by asgrim** [comment]
Fixed in [1.2.3](https://github.com/scoutapp/scout-apm-laravel/releases/tag/v1.2.3) :+1:

**Comment by joelclermont** [comment]
Thank you!!! Such speedy support! I ran into an issue (unrelated, Composer issue) and blogged about it https://joelclermont.com/post/things-to-know-when-updating-a-single-composer-package/

**Comment by asgrim** [comment]
@joelclermont you are most welcome :) Nice post, and good to know! Thanks
