### ISSUE TITLE
Q: Laravel 7 support

### ISSUE THREAD

**Issue by nea** [scoutapp/scout-apm-laravel#50]
Hi there

We wanted to try ScoutAPM just a minute ago and had to find out it does not work with Laravel 7 atm. 

When will you plan support? Right now, all deps are limited to 6.x. Are there deeper requirements to Laravel < 7, or would it be enough to increase the composer deps?

Thanks a lot

**Comment by cschneid** [comment]
Hi @nea, we're working on double-checking that Laravel 7 is all working before bumping those requirements. It's likely we "just-work" by bumping the composer deps, but we need to finish up that testing before we can deploy that.

**Comment by asgrim** [comment]
@nea I've widened the requirements to include Laravel 7.x. My preliminary testing indicates this should all work fine. L7 will work with `scout-apm-laravel:^1.3` (we just released [1.3.0](https://github.com/scoutapp/scout-apm-laravel/releases/tag/v1.3.0)!)
