### ISSUE TITLE
Feature request: support instrumenting "artisan" commands

### ISSUE THREAD

**Issue by liam-wiltshire** [scoutapp/scout-apm-laravel#54]
At the moment, Scout will not send up data for artisan commands - as far as I can tell the two ways that scout will send data are when triggered by middleware, or when triggered by a queue.

If you have 'regular' artisan commands, then no data will be sent up to scout, however it is still instrumenting database queries. The memory footprint of this is pretty small, so it's not a major drama, however we have a few artisan commands that run as long running processes (essentially a daemon that checks for certain things), and as such because they have no exit-point for scout, the DB spans just continue to increase. I guess the same would happen if someone had disabled queue instrumentation?

I guess longer term it'd be great for scout to instrument artisan commands as it does with events and http requests, but otherwise I wonder if it's possible to have a check, and only instrument DB queries if there is an active request or something?

**Comment by asgrim** [comment]
Nice suggestion - we'll have a look into this, thank you! :+1:

**Comment by asgrim** [comment]
@liam-wiltshire Support for instrumenting `artisan` commands has been added in [`scoutapp/scout-apm-php:8.6.0`](https://github.com/scoutapp/scout-apm-php/releases/tag/8.6.0) :tada:

If you wish to disable this behaviour, you have a couple of options:

 * configure `SCOUT_DISABLED_INSTRUMENTS="[\"laravel_console\"]"` in `.env` or passed to a specific command (e.g. `SCOUT_DISABLED_INSTRUMENTS="[\"laravel_console\"]" php artisan ...`
 * Set `$config[\Scoutapm\Config\ConfigKey::DISABLED_INSTRUMENTS] = ['laravel_console'];` in `config/scout_apm.php`
 * Run the command with monitoring disabled completely, e.g. `SCOUT_MONITOR=false php artisan ...`
 
Also to note, if you explicitly want to disable the `scoutapm` extension from collecting data, but still leave the PHP library performing instrumentation, you can call:

```php
if (function_exists('scoutapm_enable_instrumentation')) {
    scoutapm_enable_instrumentation(false);
}
```

to disable the extension. This will leave the `scoutapp/scout-apm-php` library monitoring, but the PHP extension `scoutapm` will not not collect any data (e.g. on DB queries, file operations etc.)
