### ISSUE TITLE
Span limit of 1500 has been reached trying to start span for "SQL/Query"

### ISSUE THREAD

**Issue by ysb** [scoutapp/scout-apm-laravel#75]
Hi;

I get Span limit of 1500 has been reached trying to start span for "SQL/Query" error on some queries. What is the reason and how can I solve this?

Thanks.

**Comment by asgrim** [comment]
This limit was introduced to stop excessively large amounts of memory from being consumed by Scout. See scoutapp/scout-apm-php#186

**Comment by ysb** [comment]
Thanks, but how can I prevent getting an exception?
Can I just set like `config(['scout.reached_span_cap' => true]);` ?

**Comment by asgrim** [comment]
It is unlikely you're seeing an exception, you're probably seeing a `notice` level message in your logs. If you don't want to see `notice` level logs, you can change the log level as per https://github.com/scoutapp/scout-apm-laravel#logging-verbosity

However, if you are seeing an actual exception, please can you send me the trace and I can look into how it can be prevented.

**Comment by ysb** [comment]
Yes my fault, It is a notice. I thought it's an error when I see it on Bugsnag.
Thanks for quick support.

**Comment by asgrim** [comment]
You're welcome! :)
