### ISSUE TITLE
Feature request: support Dingo API

### ISSUE THREAD

**Issue by fbcarpinato** [scoutapp/scout-apm-laravel#76]
Hi guys I have a Laravel 6.0 application that uses Dingo API to handle routing.

Recently I added Scout APM to debug my application but I can see that the web endpoints are not being tracked correctly.
<img width="1674" alt="Schermata 2021-05-24 alle 13 19 18" src="https://user-images.githubusercontent.com/18047094/119340323-ab4b0680-bc92-11eb-99ff-d497ebb3286b.png">

Database and background jobs work fine.

**Comment by asgrim** [comment]
Thanks for the info - we've not tried Scout out with Dingo API yet, but it's something we can consider supporting!

**Comment by asgrim** [comment]
We have now added support for Dingo API applications! You will need to upgrade `scoutapp/scout-apm-php` to [at least `8.5.0`](https://github.com/scoutapp/scout-apm-php/releases/tag/8.5.0). Thanks for the suggestion :)
