### ISSUE TITLE
ERROR: Log level WARN was not a valid PSR-3 compatible log level. Should be one of: debug, info, notice, warning, error, critical, alert, emergency

### ISSUE THREAD

**Issue by hasnatwe** [scoutapp/scout-apm-laravel#77]
Laravel: v8.55.0
PHP: 7.4

Issue: 1:
Generating optimized autoload files
Class Scoutapm\ScoutApmBundle\Twig\TwigMethods located in ./vendor/scoutapp/scout-apm-php/src/ScoutApmBundle/Twig/TwigMethods-Twig2.php does not comply with psr-4 autoloading standard. Skipping.
Class Scoutapm\ScoutApmBundle\Twig\TwigMethods located in ./vendor/scoutapp/scout-apm-php/src/ScoutApmBundle/Twig/TwigMethods-Twig3.php does not comply with psr-4 autoloading standard. Skipping.

Issue: 2:
[2021-08-21 11:43:56] staging.ERROR: Log level WARN was not a valid PSR-3 compatible log level. Should be one of: debug, info, notice, warning, error, critical, alert, emergency {"exception":"[object] (Webmozart\\Assert\\InvalidArgumentException(code: 0): Log level WARN was not a valid PSR-3 compatible log level. Should be one of: debug, info, notice, warning, error, critical, alert, emergency at /tmp/build_9de6b4cc/vendor/webmozart/assert/src/Assert.php:2060)

**Comment by asgrim** [comment]
First issue is not really a problem, but can by solved by upgrading `scoutapp/scout-apm-php` to the latest version.

The second issue tells you the valid values for the log level. You have set it to `WARN` but it should be one of the values listed in the error message you posted.

**Comment by hasnatwe** [comment]
@asgrim Actually I am seeking if these issue can be solved to keep things stable and nice. Thanks

**Comment by asgrim** [comment]
> @asgrim Actually I am seeking if these issue can be solved to keep things stable and nice. Thanks

Yes, I gave you the solutions in my previous comment, please see above :)

**Comment by hasnatwe** [comment]
@asgrim Working fine now. Thanks for quick response.
