### ISSUE TITLE
Site is throwing a 500 error - Laravel Scout Agent is starting

### ISSUE THREAD

**Issue by RTSchriner** [scoutapp/scout-apm-laravel#78]
**Description:**
I installed Scout APM on my site last night and everything was fine. This morning the site is throwing a 500 error.

**Error:**
Laravel Scout Agent is starting

**Environment:**
Laravel Version: 5.8.*

**Comment by dlanderson** [comment]
Sorry for the issue, @RTSchriner. A few questions:

* Do you have any further logs we can analyze?
* Which version of scout-apm-laravel are you running?
* Were you running the Scout PECL extension as well?

**Comment by RTSchriner** [comment]
@dlanderson: I believe I have tracked it down to the error log file permissions.

I will post more about this once I have found a solution.

**Comment by RTSchriner** [comment]
@dlanderson: So the laravel log file is being created as the `root` user instead of `www-data` which is what causes the 500 error.

Notice how the `laravel-2021-09-17.log` file has `root:root` owner and group but the others have `www-data:www-data`.

![image](https://user-images.githubusercontent.com/7471007/133895531-dbee60a5-73d2-46f3-9a50-4766123629b4.png)

Any idea what would cause this?

**Comment by RTSchriner** [comment]
> Do you have any further logs we can analyze?

No, not at this time.

> Which version of scout-apm-laravel are you running?

2.0.0

>Were you running the Scout PECL extension as well?

No, I don't believe so.

**Comment by asgrim** [comment]
@RTSchriner the log file being created with root may be caused by running `artisan` commands with `sudo` (e.g. during deployment), using a Docker environment, or at some point Apache / PHP running as root perhaps; there are numerous causes in reality, but I do not believe this is a ScoutAPM issue, as we do not request elevated permissions for anything.
