### ISSUE TITLE
Need to support new Laravel Version 9

### ISSUE THREAD

**Issue by georgi-worksite** [scoutapp/scout-apm-laravel#83]
- Scout does not support the new Laravel 9.x version yet.

https://laravel.com/docs/9.x/upgrade

**Comment by asgrim** [comment]
We'll be working on this soon!

**Comment by asgrim** [comment]
Laravel 9 support was added in [release 2.2.0](https://github.com/scoutapp/scout-apm-laravel/releases/tag/v2.2.0) - thanks!

**Comment by ghost** [comment]
Thanks
